#!/bin/bash
#SBATCH --nodes=2
#SBATCH --time=120
#SBATCH --cpus-per-task=48
#SBATCH --ntasks=2
#SBATCH --job-name="Pipeline"
#SBATCH --export=PATH,RNASEQDIR

inputFile='/home/alberton/biox221/plantINPUT'
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 1 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 2 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 3 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 4 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 5 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 6 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 7 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 8 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 9 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 10 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 11 "${inputFile}" &
srun -N1 -c48 -n1 runPipe.py --noconfirm --maxcpu 2 -e 3 -r 12 "${inputFile}" &

wait